import { useState, useEffect } from 'react'
import { Plus, Sparkles } from 'lucide-react'
import './HomePage.css'

const EXAMPLES = [
  'The Future of Renewable Energy',
  'AI in Healthcare',
  'Startup Pitch Deck',
  'Digital Marketing Strategy',
]

export default function HomePage({ onNew, onPreview, loading }) {
  const [history, setHistory] = useState([])

  useEffect(() => {
    fetch('/history')
      .then(r => r.json())
      .then(data => setHistory(data))
      .catch(console.error)
  }, [])

  return (
    <div className="home">
      <header className="home-header">
        <div className="home-logo">
          <span className="logo-icon">✦</span>
          <span>Napkin AI</span>
        </div>
      </header>

      <main className="home-main">
        <div className="home-hero">
          <h1 className="hero-title">Create stunning presentations<br />with AI</h1>
          <p className="hero-sub">Describe your topic and get a fully designed presentation in seconds.</p>

          <div className="hero-actions">
            <button className="btn-create" onClick={onNew} disabled={loading}>
              {loading ? <><span className="spinner-dark" /> Generating…</> : <><Sparkles size={16} /> Create new with AI</>}
            </button>
          </div>
        </div>

        <div className="examples-section">
          <p className="examples-label">Try an example</p>
          <div className="examples-grid">
            {EXAMPLES.map(ex => (
              <button key={ex} className="example-chip" onClick={onNew}>
                <Plus size={13} /> {ex}
              </button>
            ))}
          </div>
        </div>

        {history.length > 0 && (
          <div className="examples-section" style={{ marginTop: '40px', maxWidth: '800px', width: '100%', alignSelf: 'center' }}>
            <p className="examples-label" style={{ textAlign: 'center', marginBottom: '16px' }}>Your Previous Presentations</p>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '16px' }}>
              {history.map((item, idx) => (
                <div 
                  key={idx} 
                  onClick={() => onPreview(item)}
                  style={{ background: 'white', padding: '20px', borderRadius: '12px', cursor: 'pointer', border: '1px solid #eaeaea', display: 'flex', flexDirection: 'column', gap: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.04)', transition: 'transform 0.2s, box-shadow 0.2s' }}
                  onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)' }}
                  onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 2px 8px rgba(0,0,0,0.04)' }}
                >
                  <div style={{ fontWeight: '700', fontSize: '15px', color: '#1a1a1a', lineHeight: 1.3 }}>{item.title || "Untitled Presentation"}</div>
                  <div style={{ fontSize: '13px', color: '#666' }}>{item.slides?.length || 0} slides • {item.subtitle || 'Generated by AI'}</div>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
