import './SlideCard.css'

function ImagePanel({ query }) {
  if (!query) return null
  return (
    <div className="slide-image-panel">
      <img
        src={`/image-proxy?query=${encodeURIComponent(query)}`}
        alt={query}
        className="slide-image"
        onError={e => { e.target.style.display = 'none' }}
      />
    </div>
  )
}

function TitleSlide({ data }) {
  const coverQuery = data.cover_image_query || data.title;
  return (
    <div className="slide slide-title-layout">
      <ImagePanel query={coverQuery} />
      <div className="slide-content-panel slide-title-content">
        <h1 className="slide-main-title">{data.title}</h1>
        {data.subtitle && <p className="slide-subtitle">{data.subtitle}</p>}
        <p className="slide-meta">Generated by Napkin AI</p>
      </div>
    </div>
  )
}

function BulletsSlide({ data }) {
  return (
    <div className="slide slide-bullets-layout">
      <ImagePanel query={data.image_query} />
      <div className="slide-content-panel">
        <h2 className="slide-heading">{data.title}</h2>
        <div className="slide-divider" />
        {data.description && <p className="slide-description">{data.description}</p>}
        <ul className="slide-bullets">
          {(data.bullets || []).map((b, i) => (
            <li key={i} className="slide-bullet">
              <span className="bullet-dot">▸</span>
              <span>{b}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}

function TwoColumnSlide({ data }) {
  const left = data.left_bullets || (data.bullets || []).slice(0, 3)
  const right = data.right_bullets || (data.bullets || []).slice(3)
  return (
    <div className="slide slide-two-col-layout">
      <div className="slide-content-panel full-width">
        <h2 className="slide-heading">{data.title}</h2>
        <div className="slide-divider" />
        {data.description && <p className="slide-description">{data.description}</p>}
        <div className="two-col-grid">
          <div className="col-block">
            <div className="col-label">Key Points</div>
            <ul className="slide-bullets">
              {left.map((b, i) => <li key={i} className="slide-bullet"><span className="bullet-dot">▸</span><span>{b}</span></li>)}
            </ul>
          </div>
          <div className="col-block">
            <div className="col-label">Details</div>
            <ul className="slide-bullets">
              {right.map((b, i) => <li key={i} className="slide-bullet"><span className="bullet-dot">▸</span><span>{b}</span></li>)}
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

function QuoteSlide({ data }) {
  return (
    <div className="slide slide-quote-layout">
      <div className="slide-content-panel full-width quote-center">
        <h2 className="slide-heading">{data.title}</h2>
        <div className="slide-divider" />
        <blockquote className="slide-quote">"{data.quote}"</blockquote>
        {data.author && <p className="slide-author">— {data.author}</p>}
        {data.description && <p className="slide-description">{data.description}</p>}
      </div>
    </div>
  )
}

function StatsSlide({ data }) {
  return (
    <div className="slide slide-stats-layout">
      <div className="slide-content-panel full-width">
        <h2 className="slide-heading">{data.title}</h2>
        <div className="slide-divider" />
        <div className="stats-grid">
          {(data.stats || []).map((s, i) => (
            <div key={i} className="stat-card">
              <div className="stat-value">{s.value}</div>
              <div className="stat-label">{s.label}</div>
            </div>
          ))}
        </div>
        {data.bullets?.length > 0 && (
          <ul className="slide-bullets mt-16">
            {data.bullets.map((b, i) => <li key={i} className="slide-bullet"><span className="bullet-dot">▸</span><span>{b}</span></li>)}
          </ul>
        )}
        {data.description && <p className="slide-description">{data.description}</p>}
      </div>
    </div>
  )
}

export default function SlideCard({ item }) {
  if (item.type === 'title') return <TitleSlide data={item.data} />
  const { data } = item
  const layout = data.layout || 'bullets'
  if (layout === 'two_column') return <TwoColumnSlide data={data} />
  if (layout === 'quote') return <QuoteSlide data={data} />
  if (layout === 'stats') return <StatsSlide data={data} />
  return <BulletsSlide data={data} />
}
